/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package el7iah2;
import java.awt.FontFormatException;
import javax.swing.table.DefaultTableModel;
import el7iah2.hr.*;
import java.awt.CardLayout;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import jxl.write.WriteException;
/**
 *
 * @author ashraf_atef
 */
 ;

public class reports extends javax.swing.JFrame {
    hr h ;ResultSet rs_dept ;
DefaultTableModel model_reports;
int arr_save[];
double arr_save_total[];
DefaultTableModel model_report_elfne; CardLayout homeCard; int card_select ;
DefaultTableModel model_report_elmndob;
DefaultTableModel model_report_elmndob_elwaset;
DefaultTableModel model_report_elmo7sl;
    /**
     * Creates new form reports
     */
 Font   font  ;
    public reports(hr h) {
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/fonts/Hacen Saudi Arabia.ttf").openStream());
        } catch (FontFormatException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
            initComponents();
            this.h=h ;
            model_reports=(DefaultTableModel) jTable_reports.getModel();
             model_report_elfne=(DefaultTableModel) jTable_report_elfne.getModel();
             model_report_elmndob=(DefaultTableModel) jTable_report_elmndob.getModel();
             model_report_elmndob_elwaset=(DefaultTableModel) jTable_report_elmndob_elwaset.getModel();
             model_report_elmo7sl=(DefaultTableModel) jTable_report_elmo7sl.getModel();
              homeCard = (CardLayout) jPanel1.getLayout();
              homeCard.show(jPanel1, "card_elfne");
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_compamy_reports = new javax.swing.JPanel();
        jCheckBox_region_report = new javax.swing.JCheckBox();
        jCheckBox_ountry_report = new javax.swing.JCheckBox();
        jCheckBox_dept_report = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_reports = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_elfne_reports = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_table_elfne = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_report_elfne = new javax.swing.JTable();
        jPanel_table_elmndob = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_report_elmndob = new javax.swing.JTable();
        jPanel_elmndob_elwaset = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_report_elmndob_elwaset = new javax.swing.JTable();
        jPanel_elmo7sl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_report_elmo7sl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel_compamy_reports.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_compamy_reports.setLayout(null);

        jCheckBox_region_report.setFont(font.deriveFont(12f)
        );
        jCheckBox_region_report.setForeground(new java.awt.Color(72, 72, 72));
        jCheckBox_region_report.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox_region_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_region_reportActionPerformed(evt);
            }
        });
        jPanel_compamy_reports.add(jCheckBox_region_report);
        jCheckBox_region_report.setBounds(840, 20, 170, 23);

        jCheckBox_ountry_report.setFont(font.deriveFont(12f)
        );
        jCheckBox_ountry_report.setForeground(new java.awt.Color(72, 72, 72));
        jCheckBox_ountry_report.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox_ountry_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ountry_reportActionPerformed(evt);
            }
        });
        jPanel_compamy_reports.add(jCheckBox_ountry_report);
        jCheckBox_ountry_report.setBounds(840, 50, 170, 23);

        jCheckBox_dept_report.setFont(font.deriveFont(12f)
        );
        jCheckBox_dept_report.setForeground(new java.awt.Color(72, 72, 72));
        jCheckBox_dept_report.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox_dept_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_dept_reportActionPerformed(evt);
            }
        });
        jPanel_compamy_reports.add(jCheckBox_dept_report);
        jCheckBox_dept_report.setBounds(840, 80, 170, 23);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(2000, 461));

        jTable_reports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "الصانات التامه", "الصيانات الغير تامه", "اجمالي الصيانات", "الأعطال درجه2", "الأعطال درجه1", "الأعطال الغير تامه", "اجمالي الأعطال", "التركيبات درجه2", "التركيبات درجه1", "التركيبات الغير تامه", "اجمالي التركيبات", "الأقساط التامه", "الأقساط الغير تامه", "المبلغ المحصل من الأقساط", "الصيانات الجديديه درجه 2", "الصيانات الجديده درجه 1", "الصيانات الجديده الغير تامه", "اجمالي الصيانات الجديده"
            }
        ));
        jTable_reports.setName("إنتاجية الشركة"); // NOI18N
        jScrollPane6.setViewportView(jTable_reports);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 2000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane8.setViewportView(jPanel3);

        jPanel_compamy_reports.add(jScrollPane8);
        jScrollPane8.setBounds(20, 120, 1180, 350);
        jScrollPane8.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/icons/print-icon.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jPanel_compamy_reports.add(jLabel1);
        jLabel1.setBounds(30, 40, 48, 60);

        jLabel3.setFont(font.deriveFont(12f)
        );
        jLabel3.setForeground(new java.awt.Color(72, 72, 72));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("تقرير المحافظات");
        jPanel_compamy_reports.add(jLabel3);
        jLabel3.setBounds(1020, 50, 170, 20);

        jLabel4.setFont(font.deriveFont(12f)
        );
        jLabel4.setForeground(new java.awt.Color(72, 72, 72));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("تقرير القطاعات");
        jPanel_compamy_reports.add(jLabel4);
        jLabel4.setBounds(1020, 80, 170, 20);

        jLabel5.setFont(font.deriveFont(12f)
        );
        jLabel5.setForeground(new java.awt.Color(72, 72, 72));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("تقرير المراكز");
        jPanel_compamy_reports.add(jLabel5);
        jLabel5.setBounds(1020, 20, 170, 20);

        getContentPane().add(jPanel_compamy_reports, "card2");

        jPanel_elfne_reports.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_elfne_reports.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel_table_elfne.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_table_elfne.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable_report_elfne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "كود الفني", "اسم الفني", "عدد العمليات", "اجمالي العمليات التامه", "الصيانات", "الأعطال", "التركيبات", "الصيانات الجديده", "اجمالي فواتير التركيبات", "اجمالي فواتير الصيانات", "اجمالي فواتير الأعطال", "اجمالي فواتير الصيانات الجديده"
            }
        ));
        jTable_report_elfne.setName("عمليات الفنين"); // NOI18N
        jScrollPane1.setViewportView(jTable_report_elfne);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane5.setViewportView(jPanel2);

        jPanel_table_elfne.add(jScrollPane5);
        jScrollPane5.setBounds(0, 0, 1150, 330);
        jScrollPane5.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        jPanel1.add(jPanel_table_elfne, "card_elfne");
        jPanel_table_elfne.getAccessibleContext().setAccessibleDescription("");

        jPanel_table_elmndob.setBackground(new java.awt.Color(255, 255, 255));

        jTable_report_elmndob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "كود المندوب", "اسم المندوب", "تركيبات مع وسيط", "تركيبات بدون وسيط", "صيانات جديده مع وسيط", "صيانات جديده بدون وسيط", "التركيبات الملغاة", "الصيانات الملغاة"
            }
        ));
        jTable_report_elmndob.setName("عمليات المندوبين"); // NOI18N
        jScrollPane2.setViewportView(jTable_report_elmndob);

        javax.swing.GroupLayout jPanel_table_elmndobLayout = new javax.swing.GroupLayout(jPanel_table_elmndob);
        jPanel_table_elmndob.setLayout(jPanel_table_elmndobLayout);
        jPanel_table_elmndobLayout.setHorizontalGroup(
            jPanel_table_elmndobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        jPanel_table_elmndobLayout.setVerticalGroup(
            jPanel_table_elmndobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_table_elmndob, "card_elmndob");

        jPanel_elmndob_elwaset.setBackground(new java.awt.Color(255, 255, 255));

        jTable_report_elmndob_elwaset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "كود المندوب الوسيط", "اسم المندوب الوسيط", "التليفون", "تركيبات مع مندوب", "تركيبات بدون مندوب", "صيانات جديده مع مندوب", "صيانات جديده بدون مندوب", "التركيبات الملغاة", "الصيانات الملغاة"
            }
        ));
        jTable_report_elmndob_elwaset.setName("عمليات المندوبين الوسيطين"); // NOI18N
        jScrollPane3.setViewportView(jTable_report_elmndob_elwaset);

        javax.swing.GroupLayout jPanel_elmndob_elwasetLayout = new javax.swing.GroupLayout(jPanel_elmndob_elwaset);
        jPanel_elmndob_elwaset.setLayout(jPanel_elmndob_elwasetLayout);
        jPanel_elmndob_elwasetLayout.setHorizontalGroup(
            jPanel_elmndob_elwasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        jPanel_elmndob_elwasetLayout.setVerticalGroup(
            jPanel_elmndob_elwasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_elmndob_elwaset, "card_elmndob_elwaset");

        jPanel_elmo7sl.setBackground(new java.awt.Color(255, 255, 255));

        jTable_report_elmo7sl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "كود المحصل", "اسم المحصل", " عدد العمليات", "عدد العمليات التامه"
            }
        ));
        jTable_report_elmo7sl.setName("عمليات المحصلين"); // NOI18N
        jScrollPane4.setViewportView(jTable_report_elmo7sl);

        javax.swing.GroupLayout jPanel_elmo7slLayout = new javax.swing.GroupLayout(jPanel_elmo7sl);
        jPanel_elmo7sl.setLayout(jPanel_elmo7slLayout);
        jPanel_elmo7slLayout.setHorizontalGroup(
            jPanel_elmo7slLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        jPanel_elmo7slLayout.setVerticalGroup(
            jPanel_elmo7slLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_elmo7sl, "card_elmo7sl");

        jPanel_elfne_reports.add(jPanel1);
        jPanel1.setBounds(30, 110, 1150, 330);

        jLabel2.setFont(font.deriveFont(12f)
        );
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/icons/print-icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel_elfne_reports.add(jLabel2);
        jLabel2.setBounds(1090, 10, 50, 60);

        getContentPane().add(jPanel_elfne_reports, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_region_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_region_reportActionPerformed
        jCheckBox_ountry_report.setSelected(false);
        jCheckBox_dept_report.setSelected(false);
        jTable_reports.getColumnModel().getColumn(0).setHeaderValue("المراكز");
        select_company_report_region();
    }//GEN-LAST:event_jCheckBox_region_reportActionPerformed

    private void jCheckBox_ountry_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ountry_reportActionPerformed
        jCheckBox_dept_report.setSelected(false);
        jCheckBox_region_report.setSelected(false);
        jTable_reports.getColumnModel().getColumn(0).setHeaderValue("المحافظات");
        select_company_reports(2);
    }//GEN-LAST:event_jCheckBox_ountry_reportActionPerformed

    private void jCheckBox_dept_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_dept_reportActionPerformed
        jCheckBox_ountry_report.setSelected(false);
        jCheckBox_region_report.setSelected(false);
        jTable_reports.getColumnModel().getColumn(0).setHeaderValue("القطاعات");
        select_company_reports(1);
    }//GEN-LAST:event_jCheckBox_dept_reportActionPerformed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
       int ch=JOptionPane.showConfirmDialog(null, "للطباعه اضغط نعم و للتصدير اضغط لا ؟");
        if (ch==0)
        {
        h.print_object.set_table(jTable_reports);
        h.print_object.Load();
       h. jDialog_print.setVisible(true);
        }else if (ch==1)
        {
        try {
            // TODO add your handling code here:
            
                // TODO add your handling code here:
             h.m. ob.write_excel(jTable_reports);
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
       try {
            if (card_select == 0) {
                int ch=JOptionPane.showConfirmDialog(null, "للطباعه اضغط نعم و للتصدير اضغط لا ؟");
                       if (ch==0)
                       {
                       h.print_object.set_table(jTable_report_elfne);
                       h.print_object.Load();
                      h. jDialog_print.setVisible(true);
                       }else if (ch==1)
                       {
                               h.m.ob.write_excel(jTable_report_elfne);
                       }
            }
            
            else if (card_select == 1) {

                int ch=JOptionPane.showConfirmDialog(null, "للطباعه اضغط نعم و للتصدير اضغط لا ؟");
                       if (ch==0)
                       {
                       h.print_object.set_table(jTable_report_elmndob);
                       h.print_object.Load();
                      h. jDialog_print.setVisible(true);
                       }else if (ch==1)
                       {
                h.m.ob.write_excel(jTable_report_elmndob);
                       }
            }
            if (card_select == 2) {

                int ch=JOptionPane.showConfirmDialog(null, "للطباعه اضغط نعم و للتصدير اضغط لا ؟");
                       if (ch==0)
                       {
                       h.print_object.set_table(jTable_report_elmndob_elwaset);
                       h.print_object.Load();
                      h. jDialog_print.setVisible(true);
                       }else if (ch==1)
                       {
                h.m.ob.write_excel(jTable_report_elmndob_elwaset);
                       }
            }
            if (card_select == 3) {

                int ch=JOptionPane.showConfirmDialog(null, "للطباعه اضغط نعم و للتصدير اضغط لا ؟");
                       if (ch==0)
                       {
                       h.print_object.set_table(jTable_report_elmo7sl);
                       h.print_object.Load();
                      h. jDialog_print.setVisible(true);
                       }else if (ch==1)
                       {
                h.m.ob.write_excel(jTable_report_elmo7sl);
                       }
            }
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jLabel2MouseReleased
void make_query()
{
     try {    h.m.ob.stmt=h.m.ob.conn.createStatement();
            rs_dept=h.m.ob.stmt.executeQuery("select e.name_elkta3 , d.country , c.region from elkta3_dependant d left join elkta3 e on d.id_elkta3=e.id_elkta3 left join countries c on d.country=c.country order by e.name_elkta3 , d.country");
        
     } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    void save_state()
{
   
     arr_save=new int[]{h.arr_elsiana[1],h.arr_elsiana[0]
    ,h.arr_el3otl[2],h.arr_el3otl[1],h.arr_el3otl[0]
    ,h.arr_eltrkeb[2],h.arr_eltrkeb[1],h.arr_eltrkeb[0]
    ,h.arr_siana_gdeda[2],h.arr_siana_gdeda[1],h.arr_siana_gdeda[0],
    h.arr_el2st[1],h.arr_el2st[0]};
     
     arr_save_total=new double[]{
    h.total_elsiana ,h.total_el3otl , h.total_eltrkeb ,h.total_siana_gdeda , h.total_el2st
                   };
    
}
void reload_state()
{
   h.arr_elsiana[1]=arr_save[0];
   h.arr_elsiana[0]=arr_save[1];
   h.arr_el3otl[2]=arr_save[2];
   h.arr_el3otl[1]=arr_save[3];
   h.arr_el3otl[0]=arr_save[4];
   h.arr_eltrkeb[2]=arr_save[5];
   h.arr_eltrkeb[1]=arr_save[6];
   h.arr_eltrkeb[0]=arr_save[7];
   h.arr_siana_gdeda[2]=arr_save[8];
   h.arr_siana_gdeda[1]=arr_save[9];
   h.arr_siana_gdeda[0]=arr_save[10];
   h.arr_el2st[1]=arr_save[11];
   h.arr_el2st[0]=arr_save[12];
   
    h.total_elsiana = arr_save_total[0];
    h.total_el3otl = arr_save_total[1];
    h.total_eltrkeb = arr_save_total[2];
    h.total_siana_gdeda = arr_save_total[3];
    h.total_el2st = arr_save_total[4];
     h.model_clients_sianat.setRowCount(0);
     h.model_co_el2st.setRowCount(0);
     h.model_clients_el3otl.setRowCount(0);
     h.model_fatorh_eltrkeb.setRowCount(0);
     h.model_siana_gdeda.setRowCount(0);
}
    void get_values_from_labels(String place)
{
    h.rep2();
    
    model_reports.addRow(new Object[]{place,h.arr_elsiana[1],h.arr_elsiana[0],h.total_elsiana
    ,h.arr_el3otl[2],h.arr_el3otl[1],h.arr_el3otl[0],h.total_el3otl
    ,h.arr_eltrkeb[2],h.arr_eltrkeb[1],h.arr_eltrkeb[0],h.total_eltrkeb
    ,h.arr_el2st[1],h.arr_el2st[0],h.total_el2st
    ,h.arr_siana_gdeda[2],h.arr_siana_gdeda[1],h.arr_siana_gdeda[0],h.total_siana_gdeda});
}
    void select_company_reports(int opt)
{
    save_state();
    h.model_elkta3_info.setRowCount(0);
    model_reports.setRowCount(0);
    
        try {
          rs_dept.beforeFirst();
           String pre=""; 
       
            if (rs_dept.next())
            {
             
                pre=rs_dept.getString(opt);
                
              h.model_elkta3_info.addRow(new Object[]{rs_dept.getString(3)});
            
            
            while(rs_dept.next())
            {
                if (!pre.equals(rs_dept.getString(opt)))
                {
                    get_values_from_labels(pre);
                  //  ------------------------------------------------------------------//
                    h.model_elkta3_info.setRowCount(0);
                    pre=rs_dept.getString(opt);
                   
                    
                }
                
                     h.model_elkta3_info.addRow(new Object[]{rs_dept.getString(3)});
                
            }
             get_values_from_labels(pre);
            h.model_elkta3_info.setRowCount(0);
             }
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
 reload_state();
}
   void select_company_report_region()
   {
   h.model_elkta3_info.setRowCount(0);
    model_reports.setRowCount(0);
    save_state();
        try {
             h.m.ob.stmt=h.m.ob.conn.createStatement();
            rs_dept.beforeFirst();
             while(rs_dept.next())
            {
                h.model_elkta3_info.addRow(new Object[]{rs_dept.getString(3)});
                get_values_from_labels(rs_dept.getString(3));
                 h.model_elkta3_info.setRowCount(0);
            }
             h.model_elkta3_info.setRowCount(0);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       reload_state();
       
   }
   
   ////////////////////////////////////////////////////////////// elfne /////////////////////////////////////////////////
   /* use count with multi table http://stackoverflow.com/questions/16806837/mysql-count-with-inner-join-of-two-tables-average-join*/

   void report_elfne(String start , String end)
   {
        try {
            model_report_elfne.setRowCount(0);
            h.m.ob.stmt=h.m.ob.conn.createStatement();
          
            ResultSet rs= h.m.ob.stmt.executeQuery("select id_elfne , name_elfne , (select count(s.id_elfne) from elsiana s where f.id_elfne=s.id_elfne and"
                    + " s.date between "+"'"+start+"' and '"+end+"'"+") as siana , (select count(t.id_elfne) from eltrkebat t where f.id_elfne=t.id_elfne and date "
                    + "between "+"'"+start+"' and '"+end+"'"+" ) as trkeb , (select count(o.id_elfne) from el3otl o where f.id_elfne=o.id_elfne and date between "
                    + ""+"'"+start+"' and '"+end+"'"+") as wrong, (select count(g.id_elfne) from siana_gdeda_archive g where f.id_elfne=g.id_elfne and date between "
                    + ""+"'"+start+"' and '"+end+"'"+") as siana_gdeda ,"
                    + "(select count(*) from clients_product where( date1 between "+"'"+start+"' and '"+end+"'"+" or date2 between "+"'"+start+"' and '"+end+"'"+" or date3 between "+"'"+start+"' and '"+end+"'"+" or date5 between "+"'"+start+"' and '"+end+"'"+" or date6 between "+"'"+start+"' and '"+end+"'"+" or date7 between "+"'"+start+"' and '"+end+"'"+" ) and class <> '-' and region in (select region from countries where f.places  like  concat('%',country,'%') ) ) "
                    + "+"+"(select count(*) from elsiana s left join clients_product cs on  s.serial=cs.serial where date between "+"'"+start+"' and '"+end+"'"+" and cs.region in (select region from countries where f.places  like  concat('%',country,'%') ) )"
                    + " as num "
                    +" , (select sum(t.price) from eltrkebat t where f.id_elfne=t.id_elfne and date "
                    + "between "+"'"+start+"' and '"+end+"'"+" ) as price_trkeb "
                    +" , (select sum(s.price) from elsiana s where f.id_elfne=s.id_elfne and"
                    + " s.date between "+"'"+start+"' and '"+end+"'"+") as price_siana "
                    +", (select sum(o.price) from el3otl o where f.id_elfne=o.id_elfne and date between "
                    + ""+"'"+start+"' and '"+end+"'"+") as price_wrong "
                    +" , (select sum(g.price) from siana_gdeda_archive g where f.id_elfne=g.id_elfne and date between "
                    + ""+"'"+start+"' and '"+end+"'"+") as price_siana_gdeda "
                    
                    + " from elfne f");
            while (rs.next())
            {
                model_report_elfne.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getInt(7),rs.getInt(3)+rs.getInt(4)+rs.getInt(5)+rs.getInt(6),
                rs.getInt(3),rs.getInt(5),rs.getInt(4),rs.getInt(6),rs.getInt(8),rs.getInt(9),rs.getInt(10),rs.getInt(11)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
     void report_elmndob(String start , String end)
     {
        try {
         model_report_elmndob.setRowCount(0);
             h.m.ob.stmt=h.m.ob.conn.createStatement();
            ResultSet rs= h.m.ob.stmt.executeQuery( " select id_elmndob , name_elmndob , "
                    + "(select count(ts.id_elmndob) from eltrkebat ts where ts.id_elmndob=e.id_elmndob"
                    + " and date between "+"'"+start+"' and '"+end+"'"+" and ts.id_elmndob_elwaset is not "+null+") "
                    + "as tr_with_m, (select count(tz.id_elmndob) from eltrkebat tz where tz.id_elmndob=e.id_elmndob and date "
                    + "between "+"'"+start+"' and '"+end+"'"+" and tz.id_elmndob_elwaset is "+null+") as tr_alone , (select count(ss.id_elmndob)"
                    + " from siana_gdeda_archive ss where ss.id_elmndob=e.id_elmndob and date between "+"'"+start+"' and '"+end+"'"+""
                    + " and ss.id_elmndob_elwaset is not "+null+") as si_with_m, (select count(sz.id_elmndob) from siana_gdeda_archive sz where "
                    + "sz.id_elmndob=e.id_elmndob and date between "+"'"+start+"' and '"+end+"'"+" and sz.id_elmndob_elwaset is "+null+")"
                    + " as sz_alone , "
            +"(select count(c_t.id_elmndob) from canceled_table c_t where "
                    + "c_t.id_elmndob=e.id_elmndob and date between "+"'"+start+"' and '"+end+"'"+" and  operation='تركيب' )"
                    + " as c_t_num_t "
                    +" , (select count(c_t.id_elmndob) from canceled_table c_t where "
                    + "c_t.id_elmndob=e.id_elmndob and date between "+"'"+start+"' and '"+end+"'"+" and  operation='صيانة جديدة' )"
                    + " as c_t_num_s "
                    + "from elmndob e"
            );
            while(rs.next())
            {
                model_report_elmndob.addRow(new Object[]{
                rs.getInt(1), rs.getString(2), rs.getInt(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7) ,rs.getInt(8)
                });
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     void report_elmndob_elwaset(String start , String end)
     {
         
         try {
         model_report_elmndob_elwaset.setRowCount(0);
             h.m.ob.stmt=h.m.ob.conn.createStatement();
            ResultSet rs= h.m.ob.stmt.executeQuery( "  select id_elmndob_elwaset , name_elmndob_elwaset ,telephone  ,(select count(ts.id_elmndob_elwaset) from eltrkebat ts where ts.id_elmndob_elwaset=e.id_elmndob_elwaset and date between "+"'"+start+"' and '"+end+"'"+" and ts.id_elmndob is not "+null+") as tr_with_m, "
                    + "(select count(tz.id_elmndob_elwaset) from eltrkebat tz where tz.id_elmndob_elwaset=e.id_elmndob_elwaset and date between "+"'"+start+"' and '"+end+"'"+" and tz.id_elmndob is "+null+") as tr_alone ,"
                    + " (select count(ss.id_elmndob_elwaset) from siana_gdeda_archive ss where ss.id_elmndob_elwaset=e.id_elmndob_elwaset and date between "+"'"+start+"' and '"+end+"'"+" and ss.id_elmndob is not "+null+") as si_with_m, "
                    + "(select count(sz.id_elmndob_elwaset) from siana_gdeda_archive sz where sz.id_elmndob_elwaset=e.id_elmndob_elwaset and date between "+"'"+start+"' and '"+end+"'"+" and sz.id_elmndob is "+null+") as sz_alone "
                    +" , (select count(c_t.id_elmndob_elwaset) from canceled_table c_t where "
                    + "c_t.id_elmndob_elwaset=e.id_elmndob_elwaset and date between "+"'"+start+"' and '"+end+"'"+" and  operation='تركيب'  )"
                    + " as c_t_num_t "
                    
                    +" , (select count(c_t.id_elmndob_elwaset) from canceled_table c_t where "
                    + "c_t.id_elmndob_elwaset=e.id_elmndob_elwaset and date between "+"'"+start+"' and '"+end+"'"+" and  operation='صيانة جديدة' )"
                    + " as c_t_num_s "
                    
                    + " from elmndob_elwaset e");
            while(rs.next())
            {
                model_report_elmndob_elwaset.addRow(new Object[]{
                rs.getInt(1), rs.getString(2), rs.getString(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7),rs.getInt(8),rs.getInt(9)
                });
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
       
     }
      void report_elmo7sl(String start , String end)
      {
            try {
            model_report_elmo7sl.setRowCount(0);
            h.m.ob.stmt=h.m.ob.conn.createStatement();
          
            ResultSet rs= h.m.ob.stmt.executeQuery("select id_elmo7sl , name_elmo7sl , (select count(s.id_elmo7sl) from el2st s where f.id_elmo7sl=s.id_elmo7sl and"
                    + " s.date between "+"'"+start+"' and '"+end+"'"+") as siana ,"
                    + "(select count(*) from clients_product where date_el2st between "+"'"+start+"' and '"+end+"'"+"  and region in (select region from countries where f.places  like  concat('%',country,'%') ) ) "
                    + "+"+"(select count(*) from el2st s left join clients_product cs on  s.serial=cs.serial  where date between "+"'"+start+"' and '"+end+"'"+" and cs.region in (select region from countries where f.places  like  concat('%',country,'%') ) )"
 
              
                   + " as num from elmo7sl f");
            while (rs.next())
            {
                model_report_elmo7sl.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getInt(4),rs.getInt(3)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_dept_report;
    private javax.swing.JCheckBox jCheckBox_ountry_report;
    private javax.swing.JCheckBox jCheckBox_region_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel_compamy_reports;
    public javax.swing.JPanel jPanel_elfne_reports;
    private javax.swing.JPanel jPanel_elmndob_elwaset;
    private javax.swing.JPanel jPanel_elmo7sl;
    private javax.swing.JPanel jPanel_table_elfne;
    private javax.swing.JPanel jPanel_table_elmndob;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTable jTable_report_elfne;
    public javax.swing.JTable jTable_report_elmndob;
    public javax.swing.JTable jTable_report_elmndob_elwaset;
    public javax.swing.JTable jTable_report_elmo7sl;
    public javax.swing.JTable jTable_reports;
    // End of variables declaration//GEN-END:variables
}
